language: ruby
cache: bundler
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - 3.0
script:
  - bundle install --path vendor/bundle
  - bundle exec rspec
  - gem build egoi-ruby-client.gemspec
  - gem install ./egoi-ruby-client-1.1.6RC1.gem
